stages:
  data_ingestion:
    cmd: python mlops_onego/src/data/data_ingestion.py
    deps:
    - mlops_onego/src/data/data_ingestion.py
    params:
    - data_ingestion.test_size
    outs:
    - ./data/raw
  data_preprocessing:
    cmd: python mlops_onego/src/data/data_preprocessing.py
    deps:
    - ./data/raw
    - mlops_onego/src/data/data_preprocessing.py
    outs:
    - ./data/interim
  feature_engineering:
    cmd: python mlops_onego/src/features/feature_engineering.py
    deps:
    - ./data/interim
    - mlops_onego/src/features/feature_engineering.py
    params:
    - feature_engineering.max_features
    outs:
    - ./data/processed
  model_building:
    cmd: python mlops_onego/src/model/model_building.py
    deps:
    - ./data/processed
    - mlops_onego/src/model/model_building.py
    params:
    - model_building.learning_rate
    - model_building.max_depth
    - model_building.n_estimators
    outs:
    - mlops_onego/models/model.pkl
  model_evaluation:
    cmd: python mlops_onego/src/model/model_evaluation.py
    deps:
    - mlops_onego/models/model.pkl
    - mlops_onego/src/model/model_evaluation.py
    outs:
    - mlops_onego/reports/metrics.json
